# Generated by Django 3.2.5 on 2021-07-19 03:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=240)),
                ('num_of_credit', models.DecimalField(decimal_places=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=240)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('max_member', models.PositiveSmallIntegerField(default=3)),
                ('submission_deadline', models.DateTimeField(default=datetime.datetime(2021, 7, 19, 3, 46, 8, 596620, tzinfo=utc))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to='proposal_docs')),
                ('preferred_supervisors', models.CharField(blank=True, max_length=254)),
                ('project_name', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[(0, 'Draft'), (1, 'Ready'), (2, 'Published'), (3, 'Blocked')], default=0, max_length=100)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
