# Generated by Django 3.2.9 on 2021-11-25 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_proposalmodel_submission_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmodel',
            name='submission_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 3, 42, 45, 69308, tzinfo=utc)),
        ),
    ]
