# Generated by Django 3.2.9 on 2021-11-25 10:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0006_alter_proposalmodel_submission_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmodel',
            name='submission_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 25, 10, 30, 58, 210753, tzinfo=utc)),
        ),
    ]
