# Generated by Django 3.2.9 on 2021-11-26 04:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0007_alter_proposalmodel_submission_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmodel',
            name='title',
            field=models.CharField(default='title', max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalmodel',
            name='submission_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 26, 4, 48, 45, 425307, tzinfo=utc)),
        ),
    ]
