# Generated by Django 3.2.9 on 2021-11-29 16:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal', '0008_auto_20211126_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='P', max_length=50, verbose_name=(('Approved', 'A'), ('Pending', 'P', 'Denied', 'D')))),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_supervisors', models.CharField(blank=True, max_length=254)),
                ('project_name', models.CharField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[(0, 'Draft'), (1, 'Ready'), (2, 'Published'), (3, 'Blocked')], default=0, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=240, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proposalteammember',
            name='team',
        ),
        migrations.RemoveField(
            model_name='proposalteammember',
            name='user',
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid course Code', regex='[a-zA-Z]+-[0-9]+')]),
        ),
        migrations.AlterField(
            model_name='proposalmodel',
            name='submission_deadline',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 16, 11, 28, 44369, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='ProposalTeam',
        ),
        migrations.DeleteModel(
            name='ProposalTeamMember',
        ),
        migrations.AddField(
            model_name='proposalsubmission',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalmodel'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalsubmission'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
