# Generated by Django 3.2.9 on 2021-11-30 15:46

from django.db import migrations, models
import proposal.models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0012_alter_proposalmodel_submission_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalmodel',
            name='submission_deadline',
            field=models.DateTimeField(default=proposal.models.get_day_after_one_month),
        ),
    ]
