# Generated by Django 3.2.9 on 2021-11-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0014_auto_20211130_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalsubmission',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Published', 'Published'), ('Blocked', 'Blocked')], default=('Draft', 'Draft'), max_length=100),
        ),
    ]
