# Generated by Django 3.2.9 on 2021-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0015_alter_proposalsubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='path',
            field=models.CharField(default="media'abc.png", max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalsubmission',
            name='project_name',
            field=models.CharField(max_length=254),
        ),
    ]
