# Generated by Django 3.2.9 on 2021-12-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0016_auto_20211203_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='proposal_submission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proposal.proposalsubmission'),
            preserve_default=False,
        ),
    ]
