# Generated by Django 3.2.9 on 2021-11-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_alter_proposalmodel_submission_deadline'),
        ('fcm', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0003_tokenproxy'),
        ('account', '0002_auto_20211125_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='designation',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
